tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/boneyard'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'homebrew/x11'

brew 'bash'
brew 'bash-completion'
brew 'sqlite'
brew 'openssl'
brew 'python'
brew 'libmagic', args: ['with-python']
brew 'cmake'
brew 'mysql'
brew 'postgresql'
brew 'gcc'
brew 'git'
brew 'go'
brew 'docker'
brew 'docker-machine'
brew 'docker-machine-driver-xhyve'
brew 'boot2docker'
brew 'imagemagick', args: ['with-webp']
brew 'cask'
brew 'coreutils'
brew 'ffmpeg', args: ['with-fdk-aac', 'with-ffplay', 'with-freetype', 'with-openjpeg', 'with-theora', 'with-tools', 'with-libvpx']
brew 'gnu-sed', args: ['with-default-names']
brew 'irssi'
brew 'mongodb'
brew 'node'
brew 'nvm'
brew 'rbenv'
brew 'redis'
brew 'rethinkdb'
brew 'vim', args: ['with-lua', 'override-system-vi']
brew 'wget', args: ['with-iri']
brew 'kubectl'
brew 'jq'
brew 'watch'
brew 'terraform'
brew 'ansible'
brew 'the_silver_searcher'

cask 'dropbox'
cask 'google-chrome'
cask 'iterm2'
cask 'slate'
cask 'spotify'
